name: Deploy to ECS (Blue-Green with N-1 Task Revision)

on:
  workflow_dispatch:
    inputs:
      cluster_name:
        description: 'ECS Cluster Name'
        required: true
        default: 'bluegreen-cluster'  # You can provide a default or leave it empty
      service_name:
        description: 'ECS Service Name'
        required: true
        default: 'bluegreen-service'  # You can provide a default or leave it empty

permissions:
  id-token: write  # Allow writing ID token for authentication
  contents: read   # Allow reading the contents of the repository

jobs:
  fetch_task_def:
    runs-on: ubuntu-latest
    outputs: 
      task_definition_arn: ${{ steps.fetch_taskdef.outputs.TASK_DEFINITION_ARN }}
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-region: us-east-1
        role-to-assume: arn:aws:iam::222634373323:role/github-actions

    - name: Get the previous task definition (N-1)
      id: fetch_taskdef
      run: |
        # Fetch the N-1 task definition revision
        TASK_DEFINITION_NAME="nginx-sample"
        REGION="${{ secrets.AWS_REGION }}"
        # Fetch the N-1 task definition revision
        PREVIOUS_TASK_DEF=$(aws ecs list-task-definitions \
          --family-prefix $TASK_DEFINITION_NAME \
          --region $REGION \
          --sort DESC \
          --max-items 2 \
          --query 'taskDefinitionArns[1]' \
          --output text)

        echo "Previous Task Definition: $PREVIOUS_TASK_DEF"
        echo "TASK_DEFINITION_ARN=$PREVIOUS_TASK_DEF" >> $GITHUB_ENV

    - name: Update ECS Service with N-1 Task Definition
      run: |
        echo "Using Task Definition: $PREVIOUS_TASK_DEF"
        # Update the ECS service with the previous task definition revision
        aws ecs update-service \
          --cluster ${{ github.event.inputs.cluster_name }} \
          --service ${{ github.event.inputs.service_name }} \
          --task-definition "$TASK_DEFINITION_ARN" \
          --region ${{ secrets.AWS_REGION }}

    - name: Monitor ECS Service Deployment
      run: |
        # Wait for the ECS service to stabilize with the new task definition
        SERVICE_NAME=${{ github.event.inputs.service_name }}
        CLUSTER_NAME=${{ github.event.inputs.cluster_name }}

        # Poll until the service reaches a stable state
        until [[ $(aws ecs describe-services --cluster $CLUSTER_NAME --services $SERVICE_NAME --query "services[0].status" --output text) == "ACTIVE" ]]; do
          echo "Waiting for ECS service to stabilize..."
          sleep 30
        done
        echo "Deployment to ECS is stable and complete."


  # update_ecs:
  #   runs-on: ubuntu-latest
  #   needs: fetch_task_def
  #   steps:
  #   - name: Checkout Code
  #     uses: actions/checkout@v2

  #   - name: Set up AWS CLI
  #     uses: aws-actions/configure-aws-credentials@v3
  #     with:
  #       aws-region: ${{ secrets.AWS_REGION }}
  #       role-to-assume: arn:aws:iam::222634373323:role/github-actions
        
  #   - name: Update ECS Service with N-1 Task Definition
  #     run: |
  #       TASK_DEFINITION_ARN="${{ needs.fetch_task_def.outputs.task_definition_arn }}"
  #       echo "Using Task Definition: $TASK_DEFINITION_ARN"
  #       # Update the ECS service with the previous task definition revision
  #       aws ecs update-service \
  #         --cluster ${{ github.event.inputs.cluster_name }} \
  #         --service ${{ github.event.inputs.service_name }} \
  #         --task-definition $TASK_DEFINITION_ARN \
  #         --region ${{ secrets.AWS_REGION }}

  #   - name: Monitor ECS Service Deployment
  #     run: |
  #       # Wait for the ECS service to stabilize with the new task definition
  #       SERVICE_NAME=${{ github.event.inputs.service_name }}
  #       CLUSTER_NAME=${{ github.event.inputs.cluster_name }}

  #       # Poll until the service reaches a stable state
  #       until [[ $(aws ecs describe-services --cluster $CLUSTER_NAME --services $SERVICE_NAME --query "services[0].status" --output text) == "ACTIVE" ]]; do
  #         echo "Waiting for ECS service to stabilize..."
  #         sleep 30
  #       done
